baseURL = "https://latenews.netlify.app/"
languageCode = "en-us"
title = "Late News"
theme = "hugo-news"

[params]
author = "saqoah"
lastUpdated = "2025-03-06 01:25:14"

[menu]
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Categories"
url = "/categories/"
weight = 2

[[menu.main]]
name = "Latest"
url = "/latest/"
weight = 3

[taxonomies]
category = "categories"
tag = "tags"
