[params]
  # Main site parameters
  siteName = "Your Gumtree Clone"
  siteDescription = "Buy and sell items, services, and more locally"
  siteKeywords = "classifieds, marketplace, buy, sell, local"
  
  # Default categories (for initial setup)
  defaultCategories = [
    "Vehicles",
    "Property",
    "Jobs",
    "Services",
    "Electronics",
    "Furniture",
    "Fashion",
    "Pets"
  ]
  
  # Category icons (Font Awesome icons without the "fa-" prefix)
  categoryIcons = {
    "Vehicles" = "car",
    "Property" = "home",
    "Jobs" = "briefcase",
    "Services" = "tools",
    "Electronics" = "laptop",
    "Furniture" = "couch",
    "Fashion" = "tshirt",
    "Pets" = "paw"
  }
  
  # Social media links
  facebook = "https://facebook.com/youraccount"
  twitter = "https://twitter.com/youraccount"
  instagram = "https://instagram.com/youraccount"
  
  # Contact information
  contactEmail = "contact@yourdomain.com"
  contactPhone = "+1234567890"
  
  # Location settings
  defaultLocation = "Your Default City"
  enableLocationSelector = true
  
  # Feature toggles
  enableSearch = true
  enableCategories = true
  enableFeaturedAds = true
  enableUserAccounts = true
  
  # UI customization
  primaryColor = "#37a864"  # Gumtree-like green
  secondaryColor = "#2e3d58"  # Dark blue
