name = "gumtree-clone"
license = "MIT"
licenselink = "https://github.com/yourusername/gumtree-clone/blob/master/LICENSE"
description = "A Hugo theme clone of Gumtree.com with modern design and CDN CSS"
homepage = "https://github.com/yourusername/gumtree-clone"
tags = ["classifieds", "marketplace", "responsive", "gumtree"]
features = ["responsive", "modern", "search", "categories"]
min_version = "0.92.0"

[author]
  name = "Your Name"
  homepage = "https://yourdomain.com"