name: Fetch RSS and Commit Articles

on:
  schedule:
    - cron: "0 * * * *"  # Runs every hour
  workflow_dispatch:  # Allows manual triggering

jobs:
  fetch-and-commit:
    runs-on: ubuntu-latest

    permissions:
      contents: write  # Allows committing changes

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: pip install feedparser html2text

      - name: Run RSS script
        run: python script.py "https://www.wired.com/feed/tag/ai/latest/rss" --output "content/articles"

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit and push changes
        run: |
          git add content/articles/*.md
          git commit -m "Updated articles from RSS feed" || echo "No changes to commit"
          git push
