name: RSS to Hugo Converter

on:
  workflow_dispatch:  # Allow manual trigger

jobs:
  convert-rss:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Explicitly set permission to write to repository
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install feedparser html2text
      
      - name: Run RSS to Hugo converter
        run: python converter.py https://www.wired.com/feed/tag/ai/latest/rss --output content/articles
      
      - name: Commit changes
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add content/posts/rss/
          git diff --quiet && git diff --staged --quiet || git commit -m "Add RSS articles from feed"
          git push
